# Generated by Django 3.2 on 2021-04-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('link', models.CharField(max_length=50)),
            ],
        ),
    ]
